// Definição das fases do protótipo (8 fases — curva 4-3-2-1 reduzida).
// Idealmente, fases viram arquivos JSON editáveis por pedagogo (Dia 3).

import type { Level } from '../types';

export const LEVELS: Level[] = [
  {
    id: 1,
    diff: 0,
    lives: 3,
    title: 'Primeiros passos',
    goal: '3 inimigos',
    ops: ['+', '-'],
    handPool: [
      { op: '-', val: 1 },
      { op: '-', val: 2 },
      { op: '-', val: 3 },
      { op: '-', val: 4 },
      { op: '-', val: 5 },
    ],
    enemies: [
      { value: 3, delay: 1.5, speed: 0.16 },
      { value: 5, delay: 6.0, speed: 0.16 },
      { value: 4, delay: 11.0, speed: 0.16 },
    ],
    tutorial: 'Arraste uma carta vermelha (-) no inimigo até zerar o número!',
  },
  {
    id: 2,
    diff: 0,
    lives: 3,
    title: 'Combinando',
    goal: '4 inimigos',
    ops: ['+', '-'],
    handPool: [
      { op: '-', val: 1 },
      { op: '-', val: 2 },
      { op: '-', val: 3 },
      { op: '-', val: 5 },
      { op: '+', val: 1 },
    ],
    enemies: [
      { value: 4, delay: 1.0, speed: 0.18 },
      { value: 6, delay: 4.5, speed: 0.18 },
      { value: 7, delay: 8.5, speed: 0.18 },
      { value: 5, delay: 12.5, speed: 0.18 },
    ],
    tutorial: 'Cartas verdes (+) somam — use quando precisar ajustar o resultado!',
  },
  {
    id: 3,
    diff: 0,
    lives: 3,
    title: 'Mais inimigos',
    goal: '5 inimigos',
    ops: ['+', '-'],
    handPool: [
      { op: '-', val: 2 },
      { op: '-', val: 3 },
      { op: '-', val: 5 },
      { op: '+', val: 1 },
      { op: '+', val: 2 },
    ],
    enemies: [
      { value: 5, delay: 1.0, speed: 0.20 },
      { value: 7, delay: 4.0, speed: 0.20 },
      { value: 6, delay: 7.0, speed: 0.20 },
      { value: 8, delay: 10.0, speed: 0.20 },
      { value: 4, delay: 13.5, speed: 0.20 },
    ],
  },
  {
    id: 4,
    diff: 0,
    lives: 3,
    title: 'Acelerando',
    goal: '5 inimigos',
    ops: ['+', '-'],
    handPool: [
      { op: '-', val: 3 },
      { op: '-', val: 5 },
      { op: '-', val: 7 },
      { op: '+', val: 2 },
      { op: '+', val: 3 },
    ],
    enemies: [
      { value: 6, delay: 0.8, speed: 0.22 },
      { value: 9, delay: 3.5, speed: 0.22 },
      { value: 7, delay: 6.5, speed: 0.24 },
      { value: 10, delay: 9.0, speed: 0.22 },
      { value: 8, delay: 12.0, speed: 0.24 },
    ],
  },
  {
    id: 5,
    diff: 1,
    lives: 3,
    title: 'Onda',
    goal: '6 inimigos',
    ops: ['+', '-'],
    handPool: [
      { op: '-', val: 3 },
      { op: '-', val: 5 },
      { op: '-', val: 8 },
      { op: '+', val: 1 },
      { op: '+', val: 3 },
    ],
    enemies: [
      { value: 7, delay: 0.8, speed: 0.24 },
      { value: 9, delay: 3.0, speed: 0.24 },
      { value: 5, delay: 5.5, speed: 0.26 },
      { value: 12, delay: 7.5, speed: 0.24 },
      { value: 8, delay: 10.0, speed: 0.26 },
      { value: 10, delay: 12.5, speed: 0.26 },
    ],
  },
  {
    id: 6,
    diff: 1,
    lives: 3,
    title: 'Multiplicação',
    goal: '6 inimigos',
    ops: ['+', '-', '×'],
    handPool: [
      { op: '-', val: 4 },
      { op: '-', val: 6 },
      { op: '+', val: 2 },
      { op: '×', val: 2 },
      { op: '×', val: 0 },
    ],
    enemies: [
      { value: 6, delay: 1.0, speed: 0.24 },
      { value: 8, delay: 3.5, speed: 0.24 },
      { value: 4, delay: 6.0, speed: 0.26 },
      { value: 14, delay: 8.5, speed: 0.24 },
      { value: 9, delay: 11.0, speed: 0.26 },
      { value: 11, delay: 13.5, speed: 0.26 },
    ],
    tutorial: 'Cartas amarelas MULTIPLICAM. ×0 zera direto, ×2 dobra (cuidado!)',
  },
  {
    id: 7,
    diff: 1,
    lives: 3,
    title: 'Combinações',
    goal: '7 inimigos',
    ops: ['+', '-', '×'],
    handPool: [
      { op: '-', val: 5 },
      { op: '-', val: 8 },
      { op: '+', val: 3 },
      { op: '×', val: 2 },
      { op: '×', val: 0 },
    ],
    enemies: [
      { value: 7, delay: 0.8, speed: 0.26 },
      { value: 13, delay: 3.0, speed: 0.26 },
      { value: 8, delay: 5.5, speed: 0.28 },
      { value: 16, delay: 7.5, speed: 0.26 },
      { value: 9, delay: 10.0, speed: 0.28 },
      { value: 11, delay: 12.5, speed: 0.28 },
      { value: 14, delay: 15.0, speed: 0.28 },
    ],
  },
  {
    id: 8,
    diff: 2,
    lives: 2,
    title: 'Desafio',
    goal: '8 inimigos · 2 vidas',
    ops: ['+', '-', '×'],
    handPool: [
      { op: '-', val: 7 },
      { op: '-', val: 4 },
      { op: '+', val: 3 },
      { op: '×', val: 2 },
      { op: '×', val: 0 },
    ],
    enemies: [
      { value: 8, delay: 0.8, speed: 0.28 },
      { value: 11, delay: 2.8, speed: 0.28 },
      { value: 6, delay: 4.8, speed: 0.32 },
      { value: 18, delay: 6.5, speed: 0.28 },
      { value: 13, delay: 8.5, speed: 0.30 },
      { value: 9, delay: 10.5, speed: 0.32 },
      { value: 21, delay: 12.5, speed: 0.28 },
      { value: 15, delay: 14.5, speed: 0.30 },
    ],
  },
];
